debug:
##  true
  false
server:
  port: 8081
  servlet:
    context-path: /boot02
spring:
  profiles:
    active: prod
logging:
  level:
    pt.joja.SpringBootLogTest: trace
  file: jojaMarket.log
#  path: C:\Users\aband\Desktop\
#  pattern:
#    console: %d{yyyy-MM-dd} [%thread] %-5level %logger{50} - %msg%n
---
server:
  port: 8084
spring:
  profiles: dev
---
server:
  port: 8085
spring:
  profiles: prod
---
#person:
#  lastName: 张三
#  age: 18
#  boss: false
#  birthday: 2017/12/12
#  maps: {key1: value1, key2: value2}
#  lists:
#    - 李四
#    - 王五
#    - 小花
#    - 赵六
#  dog:
#    name: Doggie
#    age: 2
