spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.229.129:3306/jpa?serverTimeZone=UTC
      username: root
      password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true